### ISSUE TITLE
Support strange encoding patches

### ISSUE THREAD

**Issue by marxin** [marxin/gcc-changelog#2]
Git commits like gcc-mirror/gcc@8633545d6afd24cea23f19e32ab34f7ae2908522 can't be parsed with `utf8` from a `git format-patch` output:

```
$ ./changelog.py /tmp/0001-Update-.po-files.patch
Traceback (most recent call last):
  File "./changelog.py", line 503, in <module>
    email = Email(sys.argv[1])
  File "./changelog.py", line 229, in __init__
    self.diff = PatchSet.from_filename(filename)
  File "/usr/lib/python3.8/site-packages/unidiff/patch.py", line 425, in from_filename
    instance = cls(f)
  File "/usr/lib/python3.8/site-packages/unidiff/patch.py", line 353, in __init__
    self._parse(data, encoding=encoding)
  File "/usr/lib/python3.8/site-packages/unidiff/patch.py", line 399, in _parse
    current_file._parse_hunk(line, diff, encoding)
  File "/usr/lib/python3.8/site-packages/unidiff/patch.py", line 228, in _parse_hunk
    for diff_line_no, line in diff:
  File "/usr/lib64/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5005: invalid continuation byte
```

**Comment by marxin** [comment]
Apparently, `git format-patch` won't be used in production, so it should be avoidable.
